# Project: New Koala Engine
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Listener.o Parser.o Response.o Main.o
LINKOBJ  = Listener.o Parser.o Response.o Main.o
LIBS     = -L"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc definitions.h events.h ../Programs/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include/sys/stat.h Listener.h Parser.h Response.h virgo.h -m32
INCS     = -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/Franciszek/Desktop/Programs/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "New Koala Engine.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
DEL      = C:\Users\Franciszek\Desktop\Programs\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Listener.o: Listener.cpp
	$(CPP) -c Listener.cpp -o Listener.o $(CXXFLAGS)

Parser.o: Parser.cpp
	$(CPP) -c Parser.cpp -o Parser.o $(CXXFLAGS)

Response.o: Response.cpp
	$(CPP) -c Response.cpp -o Response.o $(CXXFLAGS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)
